import { CampaignBuilderState } from './campaign-builder.types';

export function buildInitialCampaignBuilderState(now = new Date()): CampaignBuilderState {
  const today = new Date(now);
  const inSevenDays = new Date(now);
  inSevenDays.setDate(inSevenDays.getDate() + 7);

  return {
    campaign: {
      name: '',
      objective: 'OUTCOME_TRAFFIC',
      initialStatus: 'PAUSED',
      specialCategory: 'Nenhuma',
      buyingType: 'Auction',
      abTest: false,
      campaignBudgetOptimization: true,
      campaignSpendLimit: null,
    },
    identity: {
      adAccountId: '',
      facebookPageId: '',
      instagramAccount: '',
      displayName: '',
      timezone: 'America/Sao_Paulo',
      currency: 'BRL',
    },
    audience: {
      autoAudience: true,
      country: 'BR',
      region: '',
      city: '',
      zipCode: '',
      radiusKm: 10,
      presenceType: 'Pessoas que moram nesta região',
      ageMin: 21,
      ageMax: 55,
      gender: 'ALL',
      languagePrimary: 'Português',
      languagesAdditional: '',
      interests: '',
      behaviors: '',
      demographics: '',
      excludedInterests: '',
      savedAudience: '',
      customAudience: '',
      lookalikeAudience: '',
      excludedAudiences: '',
    },
    budget: {
      budgetType: 'daily',
      value: 50,
      quickBudget: 50,
      adSetSpendLimit: null,
      bidStrategy: 'Highest volume',
      costControl: null,
      minRoas: null,
      costPerResultGoal: null,
      manualBid: null,
      billingEvent: 'Impressions',
      optimizationGoal: 'Link clicks',
      conversionWindow: '7-day click',
    },
    schedule: {
      startDate: today.toISOString().slice(0, 10),
      startTime: '09:00',
      endDate: inSevenDays.toISOString().slice(0, 10),
      endTime: '22:00',
      weekDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      timeBlocks: '09:00-12:00, 14:00-18:00',
      advancedScheduling: false,
    },
    placements: {
      selected: ['feed', 'stories', 'reels'],
      platforms: {
        facebook: true,
        instagram: true,
        messenger: false,
        audienceNetwork: false,
      },
    },
    destination: {
      type: 'site',
      websiteUrl: '',
      messagesDestination: '',
      formName: '',
      appLink: '',
      catalogId: '',
    },
    creative: {
      message: '',
      headline: '',
      description: '',
      cta: 'Saiba mais',
      imageUrl: '',
      carousel: false,
    },
    tracking: {
      pixel: '',
      mainEvent: 'Purchase',
      conversionTracking: 'Conversão padrão',
      utmSource: 'meta',
      utmMedium: 'paid-social',
      utmCampaign: '',
      goals: '',
      notes: '',
    },
    ui: {
      aiPrompt: '',
      aiApplied: false,
      aiDetectedFields: [],
      aiLastSummary: '',
    },
  };
}
